name: advanced_course
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # My Dependencies Here:
  flutter_svg: ^1.1.5
  retrofit: ^3.0.1+1
  analyzer: ^5.0.0
  dio: ^4.0.6
  json_serializable: ^6.4.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  freezed: ^2.1.1
  get_it: ^7.2.0
  lottie: ^1.4.3
  country_code_picker: ^3.0.0
  image_picker: ^0.8.7+1
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.1.0+1
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/json/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-semiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300


